format = """
[î‚¶](fg:#61afef)$directory\
[î‚´](fg:#61afef bg:#394260)\
$git_branch\
$git_status\
[î‚¶](fg:#212736 bg:#394260)\
$nodejs\
[î‚´](fg:#212736)\
$hostname\
\n\n$character"""

add_newline = true

[hostname]
format=' on [$ssh_symbol$hostname]($style)'
style='fg:#61afef'
ssh_symbol='î˜® '

[character]
success_symbol = '[î¬ˆ](bold fg:#61afef)'
error_symbol = '[X](bold red)'

[directory]
style = "fg:#373c4a bg:#61afef"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "../"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#61afef bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status )](fg:#61afef bg:#394260)]($style)'
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[$symbol ($version)](fg:#61afef bg:#212736)]($style)'
